- name: Install dependencies
  yum:
    name:
      - docker
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Create kubeadm configuration file
  template:
    src: kubeadm-config.yaml.j2
    dest: /root/kubeadm-config.yaml

- name: Initialize Kubernetes master
  shell: |
    kubeadm init --config /root/kubeadm-config.yaml
  when: inventory_hostname == groups['masters'][0]

- name: Set up kubeconfig for root
  shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  when: inventory_hostname == groups['masters'][0]

- name: Join other masters to the cluster
  shell: |
    kubeadm join {{ virtual_ip }}:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash> --control-plane --certificate-key <cert-key>
  when: inventory_hostname != groups['masters'][0]

- name: Join workers to the cluster
  shell: |
    kubeadm join {{ virtual_ip }}:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>
  when: inventory_hostname in groups['workers']
